[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "inventory manager"
version = "1.0.0"
[tool.poetry.dependencies]
python = "^3.8"
Cerberus = "^1.3.4"
Flask = "^2.1.2"
pymongo = {version = "^4.1.1",extras = ["srv"]}
